plugins {
    id 'io.quarkus' version "${quarkusPluginVersion}" apply false
}

allprojects {
    group = 'com.legenkiy'
    version = '0.0.1'

    repositories {
        mavenCentral()
    }
}

subprojects {
    pluginManager.withPlugin('java') {
        apply plugin: 'checkstyle'

        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        checkstyle {
            toolVersion = "${checkstyleVersion}"
        }

        test {
            useJUnitPlatform()
            systemProperty 'user.timezone', 'UTC'
        }

        dependencies {
            implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
            testImplementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

            constraints {
                compileOnly "org.projectlombok:lombok:${lombokVersion}"
                annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
                testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
                testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

                testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
                testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitPlatformVersion}"
                testImplementation "org.testcontainers:junit-jupiter:${testcontainersVersion}"
                testImplementation "org.testcontainers:postgresql:${testcontainersVersion}"
                testImplementation "com.github.database-rider:rider-junit5:${databaseRiderVersion}:jakarta"
                testImplementation "org.assertj:assertj-core:${assertjVersion}"
                testImplementation "org.skyscreamer:jsonassert:${jsonAssertVersion}"
            }
        }
    }
}
