quarkusPluginVersion=3.40.1
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.40.1
org.gradle.java.home=C:/Program Files/Java/jdk-21

lombokVersion=1.18.48
junitVersion=6.0.0
junitPlatformVersion=6.0.0
checkstyleVersion=14.3.0
testcontainersVersion=1.21.3
databaseRiderVersion=1.44.0
assertjVersion=3.27.7
jsonAssertVersion=1.5.3
