quarkus:
  datasource:
    db-kind: postgresql
    username: ${BV_POSTGRES_USERNAME}
    password: ${BV_POSTGRES_PASSWORD}
    jdbc:
      url: ${BV_POSTGRES_URL}

  hibernate-orm:
    database:
      scripts:
        generation: none

  flyway:
    migrate-at-start: true

smallrye:
  jwt:
    sign:
      key: ${JWT_PRIVATE_KEY}

mp:
  jwt:
    verify:
      publickey: ${JWT_PUBLIC_KEY}
      issuer: bidvault

jwt:
  refresh:
    expired: ${JWT_REFRESH_EXPIRED}
  access:
    expired: ${JWT_ACCESS_EXPIRED}