quarkus:
  datasource:
    db-kind: postgresql
    username: ${BV_POSTGRES_USERNAME}
    password: ${BV_POSTGRES_PASSWORD}
    jdbc:
      url: ${BV_POSTGRES_URL}

  hibernate-orm:
    database:
      scripts:
        generation: none

  flyway:
    migrate-at-start: true

  http:
    port: 8080

  index-dependency:
    bv-web:
      group-id: com.legenkiy
      artifact-id: bv-web
    bv-user:
      group-id: com.legenkiy
      artifact-id: bv-user
    bv-common:
      group-id: com.legenkiy
      artifact-id: bv-common

smallrye:
  jwt:
    sign:
      key:
        location: jwt/privateKey.pem


mp:
  jwt:
    verify:
      publickey:
        location: jwt/publicKey.pem
      issuer: bidvault

jwt:
  refresh:
    expired: ${JWT_REFRESH_EXPIRED}
  access:
    expired: ${JWT_ACCESS_EXPIRED}
