plugins {
    id 'java-library'
}

dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation(project(':bv-user'))
    implementation(project(':bv-common'))

    implementation 'io.quarkus:quarkus-rest-jackson'
    implementation 'io.quarkus:quarkus-smallrye-jwt'
    implementation 'io.quarkus:quarkus-smallrye-jwt-build'
    implementation 'io.quarkus:quarkus-elytron-security-common'
    implementation 'io.quarkus:quarkus-hibernate-validator'
}
